language: java

dist: trusty

branches:
  only:
  - master
  
script:
  - cd api
  - mvn clean package
  - cd ..
  - cd first-connector
  - mvn clean package

cache:
  directories:
  - '$HOME/.m2/repository'
