version: "3.7"

services:
  elasticsearch:
    container_name: elasticsearch
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:6.8.7
    ports:
      - 5601:5601

  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

# rabbitmq-plugins enable rabbitmq_stomp